-- StudyBench production schema reference

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  unlimited_until timestamptz,
  is_admin boolean not null default false
);

create table if not exists public.usage_log (
  user_id uuid primary key references auth.users(id) on delete cascade,
  count int not null default 0,
  window_start timestamptz not null default now()
);

create table if not exists public.books (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null,
  wing text not null check (wing in ('educational', 'web3')),
  description text not null,
  is_free boolean not null default true,
  status text not null default 'draft' check (status in ('draft', 'published')),
  amazon_query text,
  content text,
  source_url text,
  source_name text,
  license_name text,
  license_url text,
  attribution_text text,
  source_file_url text,
  hosted_file_url text,
  storage_path text,
  hosted_parts jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_log (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount_kobo integer not null,
  currency text not null,
  paid_at timestamptz not null default now(),
  unlimited_until timestamptz not null
);

alter table public.profiles enable row level security;
alter table public.usage_log enable row level security;
alter table public.books enable row level security;
alter table public.payment_log enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  );
$$;

create or replace function public.apply_verified_payment(
  p_user_id uuid,
  p_reference text,
  p_amount_kobo integer,
  p_currency text,
  p_paid_at timestamptz
)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  current_until timestamptz;
  new_until timestamptz;
begin
  select unlimited_until into current_until
  from public.profiles
  where id = p_user_id
  for update;

  if current_until is null or current_until < now() then
    new_until := now() + interval '365 days';
  else
    new_until := current_until + interval '365 days';
  end if;

  insert into public.payment_log(reference, user_id, amount_kobo, currency, paid_at, unlimited_until)
  values (p_reference, p_user_id, p_amount_kobo, upper(p_currency), coalesce(p_paid_at, now()), new_until);

  insert into public.profiles(id, unlimited_until)
  values (p_user_id, new_until)
  on conflict (id) do update set unlimited_until = excluded.unlimited_until;

  return new_until;
end;
$$;

drop policy if exists "Public can view published books" on public.books;
create policy "Public can view published books"
on public.books for select to anon, authenticated
using (status = 'published');

drop policy if exists "Admins can manage books" on public.books;
create policy "Admins can manage books"
on public.books for all to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Admins can read profiles" on public.profiles;
create policy "Admins can read profiles"
on public.profiles for select to authenticated
using (public.is_admin_user());

drop policy if exists "Admins can read usage log" on public.usage_log;
create policy "Admins can read usage log"
on public.usage_log for select to authenticated
using (public.is_admin_user());

revoke all on public.books from anon;
grant select on public.books to anon;
revoke all on public.books from authenticated;
grant select, insert, update, delete on public.books to authenticated;
revoke all on public.profiles from anon;
revoke all on public.usage_log from anon;
revoke all on public.payment_log from anon, authenticated;
revoke all on public.profiles from authenticated;
revoke all on public.usage_log from authenticated;
grant select on public.profiles to authenticated;
grant select on public.usage_log to authenticated;

grant select, insert, update, delete on public.books to service_role;
grant select, insert, update, delete on public.profiles to service_role;
grant select, insert, update, delete on public.usage_log to service_role;
grant select, insert, update, delete on public.payment_log to service_role;
revoke all on function public.apply_verified_payment(uuid,text,integer,text,timestamptz) from public, anon, authenticated;
grant execute on function public.apply_verified_payment(uuid,text,integer,text,timestamptz) to service_role;

insert into storage.buckets (id, name, public)
values ('textbooks', 'textbooks', true)
on conflict (id) do update set public = excluded.public;
